/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.karimandco.cv;

/**
 *
 * @author t.normand
 */
public class ListeCV extends javax.swing.JDialog {

    javax.swing.JDialog panneauPereMesCV = null;
    
    /**
     * Creates new form ListeCV
     */
    public ListeCV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableInfo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonCreerUtilisateur = new javax.swing.JButton();
        jButtonCreerUtilisateur1 = new javax.swing.JButton();
        jButtonCreerUtilisateur2 = new javax.swing.JButton();

        jTableInfo.setBackground(new java.awt.Color(255, 255, 255));
        jTableInfo.setForeground(new java.awt.Color(0, 0, 0));
        jTableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "Titre du CV", "Signature"
            }
        ));
        jScrollPane1.setViewportView(jTableInfo);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("< LISTE DE MES CV >");

        jButtonCreerUtilisateur.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCreerUtilisateur.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jButtonCreerUtilisateur.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreerUtilisateur.setText("Modifier un CV");
        jButtonCreerUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerUtilisateurActionPerformed(evt);
            }
        });

        jButtonCreerUtilisateur1.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCreerUtilisateur1.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jButtonCreerUtilisateur1.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreerUtilisateur1.setText("Supprimer un CV");
        jButtonCreerUtilisateur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerUtilisateur1ActionPerformed(evt);
            }
        });

        jButtonCreerUtilisateur2.setBackground(new java.awt.Color(0, 0, 0));
        jButtonCreerUtilisateur2.setFont(new java.awt.Font("Segoe UI Black", 0, 11)); // NOI18N
        jButtonCreerUtilisateur2.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCreerUtilisateur2.setText("Créer un nouveau CV");
        jButtonCreerUtilisateur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreerUtilisateur2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCreerUtilisateur2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreerUtilisateur1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCreerUtilisateur2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreerUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreerUtilisateur1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCreerUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerUtilisateurActionPerformed
       
    }//GEN-LAST:event_jButtonCreerUtilisateurActionPerformed

    private void jButtonCreerUtilisateur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerUtilisateur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreerUtilisateur1ActionPerformed

    private void jButtonCreerUtilisateur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreerUtilisateur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCreerUtilisateur2ActionPerformed

     public void setFenParentMesCV(javax.swing.JDialog i) {
        this.panneauPereMesCV = i;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreerUtilisateur;
    private javax.swing.JButton jButtonCreerUtilisateur1;
    private javax.swing.JButton jButtonCreerUtilisateur2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableInfo;
    // End of variables declaration//GEN-END:variables
}
